function r2h = restriction(rh)
   
    n = length(rh);
    ind = 3:2:n-2;
    m = (n+1)/2;
    r2h = zeros(m,m);
    r2h(2:m-1,2:m-1) = 1/16*( ...
                        rh(ind - 1,ind - 1) + ...
                        rh(ind - 1,ind + 1) + ...
                        rh(ind + 1,ind - 1) + ...
                        rh(ind + 1,ind + 1) + ...
                        2*rh(ind + 1,ind) + ...
                        2*rh(ind - 1,ind) + ...
                        2*rh(ind,ind + 1) + ...
                        2*rh(ind,ind - 1) + ...
                        4*rh(ind,ind));

end